/**
 * Los 28 valores reales de `equipment` en el dataset (verificados contra
 * data/exercises.json antes de este plan) — universo cerrado, se
 * hardcodea igual que PARTES_CUERPO.
 */
export const EQUIPAMIENTOS = [
  'assisted',
  'band',
  'barbell',
  'body weight',
  'bosu ball',
  'cable',
  'dumbbell',
  'elliptical machine',
  'ez barbell',
  'hammer',
  'kettlebell',
  'leverage machine',
  'medicine ball',
  'olympic barbell',
  'resistance band',
  'roller',
  'rope',
  'skierg machine',
  'sled machine',
  'smith machine',
  'stability ball',
  'stationary bike',
  'stepmill machine',
  'tire',
  'trap bar',
  'upper body ergometer',
  'weighted',
  'wheel roller',
].sort();

export const ETIQUETA_EQUIPAMIENTO: Record<string, string> = {
  assisted: 'Asistido',
  band: 'Banda elástica',
  barbell: 'Barra',
  'body weight': 'Peso corporal',
  'bosu ball': 'Bosu',
  cable: 'Polea',
  dumbbell: 'Mancuerna',
  'elliptical machine': 'Elíptica',
  'ez barbell': 'Barra Z',
  hammer: 'Máquina hammer',
  kettlebell: 'Kettlebell',
  'leverage machine': 'Máquina de palanca',
  'medicine ball': 'Balón medicinal',
  'olympic barbell': 'Barra olímpica',
  'resistance band': 'Banda de resistencia',
  roller: 'Rodillo',
  rope: 'Cuerda',
  'skierg machine': 'Máquina de esquí (SkiErg)',
  'sled machine': 'Trineo',
  'smith machine': 'Máquina Smith',
  'stability ball': 'Pelota de estabilidad',
  'stationary bike': 'Bicicleta fija',
  'stepmill machine': 'Escaladora',
  tire: 'Neumático',
  'trap bar': 'Barra hexagonal',
  'upper body ergometer': 'Ergómetro de brazos',
  weighted: 'Con peso adicional',
  'wheel roller': 'Rueda abdominal',
};
